# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

registries:
  cms_sdk_registry:
    type: maven-repository
    url: https://github.com/M1troll/private_repo
    username: M1troll
    password: ${{secrets.USER_PAT}}

updates:
  - package-ecosystem: pip
    directory: "/"
    registries: "*"
    schedule:
      interval: daily
      time: "08:42"
    commit-message:
      prefix: "[automated-commit] "
    labels:
      - "automated-pr"
    groups:
      pip:
        patterns:
        - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "08:42"
    commit-message:
      prefix: "[automated-commit] "
    labels:
      - "automated-pr"
    groups:
      github-actions:
        patterns:
        - "*"
