name: 'Dependency Review'

on: [pull_request]

  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Browser in which the tests will be run
        required: true
        options:
          - all
          - chrome
          - firefox
          - edge

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
